version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: notes-postgres
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: notesuser
      POSTGRES_PASSWORD: notespass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - notes-network

  # Spring Boot Backend (Development Mode)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: notes-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/notesdb
      SPRING_DATASOURCE_USERNAME: notesuser
      SPRING_DATASOURCE_PASSWORD: notespass
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - notes-network
    volumes:
      - ./backend/src:/app/src  # Live reload for Java changes

  # React Frontend (Development Mode)
  frontend:
    image: node:18-alpine
    container_name: notes-frontend-dev
    working_dir: /app
    command: sh -c "npm install && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - notes-network
    volumes:
      - ./frontend:/app  # Live reload for React changes
      - /app/node_modules

volumes:
  postgres_data:

networks:
  notes-network:
    driver: bridge